services:
  ningyangtv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ningyangtv
    environment:
      - MAX_RETRIES=0
    restart: unless-stopped
    networks:
      - ningyangtv-net

networks:
  ningyangtv-net:
    external: true
